apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: crud-golang
data:
  POSTGRES_DB: "postgres"
  POSTGRES_USER: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "postgres"
  APP_HOST: "localhost"
  APP_PORT: "3004"
  KC_HOST: "keycloak"
  KC_PORT: "8080"
  KC_REALM_NAME: "employee_realm"
  KEYCLOAK_ADMIN: "admin"
  
    