apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: crud-golang
type: Opaque
data:
  DB_PASSWORD: Ym9va2luZw==
  DB_USER: Ym9va2luZw==
  POSTGRES_PASSWORD: Ym9va2luZw==
  POSTGRES_USER: Ym9va2luZw==
  